sudo: required
dist: trusty
language: cpp
cache: apt
arch:
  - arm64 
  - amd64
  - ppc64el
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - qt55base
      - libbotan1.10-dev
      - wget
      - tar

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

branches:
  only:
    - 'master'

before_install:
  - eval "${MATRIX_EVAL}"
  - wget -c http://download.qt.io/development_releases/qt/5.6/5.6.0-rc/single/qt-everywhere-opensource-src-5.6.0-rc.tar.xz
  - tar -czvf qt-everywhere-opensource-src-5.6.0-rc.tar.xz
  - cd qt-everywhere-opensource-src-5.6.0-rc
  - sudo  ./configure \
	    -prefix /usr
	    -confirm-license \
	    -opensource \
	    -compile-examples \
	    -shared \
	    -release  \
	    -optimized-qmake \
	    -opengl \  
	    -pch \
	    -qt-libjpeg \
	    -qt-libpng \
	    -qt-zlib \
	    -tslib \
	    -no-linuxfb \
	    -no-sse2 \
	    -no-openssl \
	    -no-cups \
	    -no-glib \
	    -no-xcb \
	    -no-separate-debug-info \
	    -skip qtcanvas3d \ 
	    -skip qt3d \
	    -nomake examples \
	    -nomake tools \
	    -nomake tests \
	    -no-iconv 
script:
  # Build
  - mkdir build && cd build
  - cmake .. -DQt5Core_DIR="/opt/qt55/lib/cmake/Qt5Core" -DQt5Network_DIR="/opt/qt55/lib/cmake/Qt5Network" -DQt5Test_DIR="/opt/qt55/lib/cmake/Qt5Test"
  - make && make test

